### ISSUE TITLE
Explain name (FTN)

### ISSUE THREAD

**Issue by mickhansen** [criipto/criipto-jwt-viewer#8]
Has unintuive value "_19cfbd642c4a82b08613b841caf0e153c5956c14" https://docs.criipto.com/verify/e-ids/finnish-trust-network/

**Comment by sgryt** [comment]
That is a commonly field, I suppose the viewer will need more context-info to figure out the correct tooltip value to show ?

**Comment by sgryt** [comment]
The value in the `name` field (at least for the Telia FTN provider) can be either an actual display name (when available for the user), or else it will be the `sub` value received from Telia.

**Comment by mickhansen** [comment]
> That is a commonly field, I suppose the viewer will need more context-info to figure out the correct tooltip value to show ?

Yes, but the overall payload should be available so can check `identityscheme` when looking at claim name.
